FROM nginx:1.15

ADD ./infrastructure/web/default.conf /etc/nginx/conf.d/default.conf

COPY --chown=nginx:nginx ./public /var/www/html/public/

# give nginx permission to serve
#RUN chown -R nginx:nginx /var/www/html/public

WORKDIR /var/www/html

